find_package(ZLIB) 
if(ZLIB_FOUND)
    set (ZLIB_INTERNAL FALSE)
    message(STATUS "Lib ZLIB FOUND.")
    message(STATUS "THE LIBRARY: ${ZLIB_LIBRARY}")
    message(STATUS "INCLUDE DIR: ${ZLIB_INCLUDE_DIR}")
else(ZLIB_FOUND)
    message(STATUS "LIB ZLIB NOT found.")
    message(STATUS "We Will build it internally")
    set (ZLIB_INTERNAL TRUE)
    set(ZLIB_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/ExternalLibs/SDL2_image-2.0.3/external/zlib-1.2.11)
    set (ZLIB_LIBRARY "zlibstatic")
    set (ZLIB_FOUND TRUE)
endif(ZLIB_FOUND)
