set(SGF_PUBLIC_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/SGF.h
${CMAKE_SOURCE_DIR}/Gamecore/tiffconfig.h
${CMAKE_SOURCE_DIR}/Gamecore/SGF_Config.h
${CMAKE_SOURCE_DIR}/Gamecore/SGF_Global.h
${CMAKE_SOURCE_DIR}/Gamecore/SGF_Types.h)
set(SGF_AI_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/ai/all.h
${CMAKE_SOURCE_DIR}/Gamecore/ai/SGF_AstarHeap.h
${CMAKE_SOURCE_DIR}/Gamecore/ai/SGF_AstarLib.h
${CMAKE_SOURCE_DIR}/Gamecore/ai/SGF_Behavior.h
${CMAKE_SOURCE_DIR}/Gamecore/ai/SGF_Map.h
${CMAKE_SOURCE_DIR}/Gamecore/ai/SGF_PathFinder.h

)
set(SGF_CONFIGURATION_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/configuration/all.h
${CMAKE_SOURCE_DIR}/Gamecore/configuration/SGF_CmdVars.h
${CMAKE_SOURCE_DIR}/Gamecore/configuration/SGF_Configuration.h
${CMAKE_SOURCE_DIR}/Gamecore/configuration/SGF_SysVars.h
${CMAKE_SOURCE_DIR}/Gamecore/configuration/SGF_SysVarsyyy.h

)
set(SGF_ENVIRONMENT_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/environment/all.h
)
set(SGF_EXCEPTIONS_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/all.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_Error.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_Exception.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_FileExceptions.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_LoadException.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_MenuException.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_MugenException.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_NetException.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_ShutdownException.h
${CMAKE_SOURCE_DIR}/Gamecore/exceptions/SGF_TokenException.h

)
set(SGF_EXTERNAL_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/external/all.h
${CMAKE_SOURCE_DIR}/Gamecore/external/DT_drawtext.h
${CMAKE_SOURCE_DIR}/Gamecore/external/SDL_console.h
${CMAKE_SOURCE_DIR}/Gamecore/external/SDL_framerate.h
${CMAKE_SOURCE_DIR}/Gamecore/external/fastevents.h
${CMAKE_SOURCE_DIR}/Gamecore/external/glSDL.h
${CMAKE_SOURCE_DIR}/Gamecore/external/internal.h
${CMAKE_SOURCE_DIR}/Gamecore/external/scale2x.h

)
set(SGF_GAME_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/game/all.h
${CMAKE_SOURCE_DIR}/Gamecore/game/SGF_Command.h
${CMAKE_SOURCE_DIR}/Gamecore/game/SGF_Console.h
${CMAKE_SOURCE_DIR}/Gamecore/game/SGF_Control.h
${CMAKE_SOURCE_DIR}/Gamecore/game/SGF_Mod.h
${CMAKE_SOURCE_DIR}/Gamecore/game/SGF_Stage.h
${CMAKE_SOURCE_DIR}/Gamecore/game/SGF_World.h

)
set(SGF_GEOMETRY_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/geometry/all.h
${CMAKE_SOURCE_DIR}/Gamecore/geometry/SGF_DrawVert.h
${CMAKE_SOURCE_DIR}/Gamecore/geometry/SGF_JointTransform.h
${CMAKE_SOURCE_DIR}/Gamecore/geometry/SGF_TraceModel.h
)
set(SGF_GRAPHICS_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/graphics/all.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_Bitmap.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_Color.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_FireEffect.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_GradientEffect.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_LitBitmap.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_Poligon.h
${CMAKE_SOURCE_DIR}/Gamecore/graphics/SGF_TransBitmap.h

)
set(SGF_GUI_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/gui/all.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_BoundBox.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_Box.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_ContextBox.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_Coordinate.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_FadetoolGui.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_GuiAnimation.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_GuiTimer.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_LineEdit.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_PopupBox.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_Rectarea.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_ScrollList.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_SelectList.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_TabbedBox.h
${CMAKE_SOURCE_DIR}/Gamecore/gui/SGF_Widget.h

)
set(SGF_INPUT_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/input/all.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_ButtonMapping.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_Events.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_FrameControl.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_Input.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_InputManager.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_InputMap.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_InputSource.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_Joystick.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_KeyMapping.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_Keyboard.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_Mouse.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_PSPJoystick.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_StructsInput.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_TextInput.h
${CMAKE_SOURCE_DIR}/Gamecore/input/SGF_WIIJoystick.h
${CMAKE_SOURCE_DIR}/Gamecore/input/newInput.h
${CMAKE_SOURCE_DIR}/Gamecore/input/sdl-joystick.h

)
set(SGF_LEVEL_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/level/all.h
${CMAKE_SOURCE_DIR}/Gamecore/level/SGF_LevelUtils.h
)
set(SGF_LISTS_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/lists/all.h
${CMAKE_SOURCE_DIR}/Gamecore/lists/SGF_AirList.h
${CMAKE_SOURCE_DIR}/Gamecore/lists/SGF_ImageList.h
${CMAKE_SOURCE_DIR}/Gamecore/lists/SGF_PcxList.h
${CMAKE_SOURCE_DIR}/Gamecore/lists/SGF_SndList.h
${CMAKE_SOURCE_DIR}/Gamecore/lists/liststructs.h

)
set(SGF_MATH_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/math/all.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Plane.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Angles.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Complex.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Curve.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Extrapolate.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Interpolation.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Lincp.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Math.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Matriz.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Odife.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Plane.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_PlaneList.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Pluecker.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Polynomial.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Quaternion.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Random.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Rotation.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Simd.h
${CMAKE_SOURCE_DIR}/Gamecore/math/SGF_Vector.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_3DNow.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_AltiVec.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_Generic.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_MMX.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_SSE.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_SSE2.h
${CMAKE_SOURCE_DIR}/Gamecore/math/Simd_SSE3.h

)
set(SGF_MENU_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/menu/all.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_ActionFactory.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_ActionSpeed.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_Menu.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_MenuAction.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_MenuAnimation.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_MenuGlobal.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_MenuOption.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_MenuV2.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionAdventure.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionAdventureCpu.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionChangeMod.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionConfig.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionCredits.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionDummy.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionFactory.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionFullScreen.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionFullscreen.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionInvencible.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionJoystick.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionKey.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionLevel.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionLives.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionMenu.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionNetworkHost.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionNetworkJoin.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionNpcBuddies.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionPlayMode.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionQuit.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionScreenSize.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionSelectFontV2.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionSpeed.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionTabMenu.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_OptionVersus.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_StructsMenu.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/SGF_TabMenu.h
${CMAKE_SOURCE_DIR}/Gamecore/menu/options.h

)
set(SGF_MUGEN_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/all.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/Configuration.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/Expression.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/Modifier.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/Section.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/Stack.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/Value.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/argument.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/ast.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/ast/astManager.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/attribute-array.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/attribute-keyword.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/attribute-simple.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/attribute.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/collectable.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/exception.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/extra.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/filename.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/function.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/helper.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/hitdef.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/identifier.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/key.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/keyword-array.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/keyword.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/number.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/operand.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/range.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/resource.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/string.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/value-list.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/variable.h
${CMAKE_SOURCE_DIR}/Gamecore/mugen/Ast/walker.h

)
set(SGF_MUGEN2_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/mugen/gc.h
)
set(SGF_NETWORK_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/network/all.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_NetChat.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_NetChatClient.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_NetChatServer.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_NetChatWidget.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_NetClient.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_NetServer.h
${CMAKE_SOURCE_DIR}/Gamecore/network/SGF_Network.h

)
set(SGF_OBJECTS_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/objects/all.h
${CMAKE_SOURCE_DIR}/Gamecore/objects/SGF_Element.h
${CMAKE_SOURCE_DIR}/Gamecore/objects/SGF_Object.h
${CMAKE_SOURCE_DIR}/Gamecore/objects/SGF_ObjectCollidable.h
${CMAKE_SOURCE_DIR}/Gamecore/objects/SGF_ObjectMessages.h
${CMAKE_SOURCE_DIR}/Gamecore/objects/SGF_ObjectNonAttack.h

)
set(SGF_RESOURCE_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/resource/all.h
${CMAKE_SOURCE_DIR}/Gamecore/resource/SGF_Collector.h
${CMAKE_SOURCE_DIR}/Gamecore/resource/SGF_FontRender.h
${CMAKE_SOURCE_DIR}/Gamecore/resource/SGF_ResourceManager.h

)
set(SGF_SCRIPT_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/script/all.h
${CMAKE_SOURCE_DIR}/Gamecore/script/SGF_Perl.h
${CMAKE_SOURCE_DIR}/Gamecore/script/SGF_Scripting.h

)
set(SGF_SPRITE_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/sprite/all.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/DrawRle.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/SGF_Efects.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/SGF_MugenSprite.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/SGF_RleSprite.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/SGF_SffManager.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/SGF_SffSprMan.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/defs.h
${CMAKE_SOURCE_DIR}/Gamecore/sprite/sprite.h

)
set(SGF_STRUCTURES_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/structures/all.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/BTree.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/BinSearch.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/Hierarchy.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_BHeap.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_Btree.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_Btree_old.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_DynamicArray.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_HashTable.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_HashTableFast.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_LinkList.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_List.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_ListString.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_Parameter.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_Queue.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_Stack.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/SGF_StackString.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/StaticList.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/StrPool.h
${CMAKE_SOURCE_DIR}/Gamecore/structures/VectorSet.h

)
set(SGF_SYS_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/sys/all.h
${CMAKE_SOURCE_DIR}/Gamecore/sys/SGF_System.h
)
set(SGF_UTIL_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/util/all.h
${CMAKE_SOURCE_DIR}/Gamecore/util/AirManager.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_ArgsCmdLine.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_AudioSystem.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_BHeap.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Callback.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Compress.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Debug.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Displayable.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Ebox.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_FileSystem.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_FilesystemBase.cpp
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_FilesystemBase.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_FontInfo.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_FontSystem.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_HashUtils.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Heap.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_LanguageString.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Loading.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_MessageQueue.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Messages.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_MugenSound.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Parameter.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Path.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Pointer.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Regex.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_SdlManager.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_SndManager.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_SoundManager.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_StringUtils.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Thread.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Timedif.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Timer.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Token.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_TokenReader_xml.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Utf.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Util.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_UtilStructs.h
${CMAKE_SOURCE_DIR}/Gamecore/util/SGF_Xmltools.h
${CMAKE_SOURCE_DIR}/Gamecore/util/all_fonts.h
${CMAKE_SOURCE_DIR}/Gamecore/util/all_messages.h
${CMAKE_SOURCE_DIR}/Gamecore/util/all_sound.h
${CMAKE_SOURCE_DIR}/Gamecore/util/tokenreader.h
${CMAKE_SOURCE_DIR}/Gamecore/util/XmlNode/CmnHdr.h
${CMAKE_SOURCE_DIR}/Gamecore/util/XmlNode/Portable.h
${CMAKE_SOURCE_DIR}/Gamecore/util/XmlNode/XmlNode.h


)
set(SGF_SDLMIXER_HDRS
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL2_mixer-2.0.2/SDL_mixer.h
)
set(SGF_SDLIMAGE_HDRS
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL2_image-2.0.0/SDL_image.h
 )

set(SGF_SDLTTF_HDRS
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL2_ttf-2.0.12/SDL_ttf.h
)
set(SGF_GFX_HDRS
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL_gfx-2.0.24/SDL_framerate.h
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL_gfx-2.0.24/SDL_gfxBlitFunc.h
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL_gfx-2.0.24/SDL_gfxPrimitives.h
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL_gfx-2.0.24/SDL_gfxPrimitives_font.h
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL_gfx-2.0.24/SDL_imageFilter.h
${CMAKE_SOURCE_DIR}/ExternalLibs/SDL_gfx-2.0.24/SDL_rotozoom.h
)

set( SGF_COMPILER_CMD_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/compiler/CmdCompiler/cmd_driver.h
)
set( SGF_COMPILER_DEF_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/compiler/DefCompiler/def_driver.h
)
set( SGF_COMPILER_AIR_HDRS
${CMAKE_SOURCE_DIR}/Gamecore/compiler/AirCompiler/air_driver.h
)

set( SGF_HAWKNL_HDRS

${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/group.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/hawklib.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/hawkthreads.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/htinternal.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/ipx.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/loopback.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/nl.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/nlinternal.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/parallel.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/serial.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/sock.h
${CMAKE_SOURCE_DIR}/ExternalLibs/hawknl/hawknl/wsock.h
)

set( SGF_EXPATL_HDRS
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/amigaconfig.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/ascii.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/asciitab.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/expat.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/expat_external.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/iasciitab.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/internal.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/latin1tab.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/macconfig.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/nametab.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/utf8tab.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/winconfig.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/xmlrole.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/xmltok.h
${CMAKE_SOURCE_DIR}/ExternalLibs/expat-2.1.0/lib/xmltok_impl.h
)
set( SGF_SGE_HDRS
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sge.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sge_bm_text.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgearray.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgecontrol.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgedefines.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgeevent.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgefadefx.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgefont.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgegamestate.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgegfx.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgegp2x.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgeinit.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgelist.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgemisc.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgeparticles.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgepathfinder.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgeresource.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgescreen.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgesound.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgesprite.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgespritegroup.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgespriteimage.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgestage.h
${CMAKE_SOURCE_DIR}/ExternalLibs/sge2d/include/sgestring.h
)
