# cmake/modules/TestSignalType.cmake
#

  MESSAGE(STATUS "Check for <bits/atomicity.h>")
  TRY_COMPILE(CMAKE_TEST_BITS_ATOMIC
    ${CMAKE_BINARY_DIR}
    ${CMAKE_SOURCE_DIR}/cmake/TestBitsAtomic.cpp
    OUTPUT_VARIABLE OUTPUT)

TRY_COMPILE(CMAKE_TEST_BITS_ATOMIC_CXX
  ${CMAKE_BINARY_DIR}
  ${CMAKE_SOURCE_DIR}/cmake/TestBitsAtomicCXX.cpp
  OUTPUT_VARIABLE OUTPUT)

  IF (CMAKE_TEST_BITS_ATOMIC)
     MESSAGE(STATUS "Check for <bits/atomicity.h>  - found")
    SET (HAVE_GCC_BITS_ATOMIC_VOID ON)
    
  ELSE (CMAKE_TEST_BITS_ATOMIC)
    MESSAGE(STATUS "Check for <bits/atomicity.h>  - not found")
   
  ENDIF (CMAKE_TEST_BITS_ATOMIC)

  IF (CMAKE_TEST_BITS_ATOMIC_CXX)
     MESSAGE(STATUS "Check for <bits/atomicity.h> CXX namespace - found")
    SET (HAVE_GCC_BITS_ATOMIC_CXX ON)

  ELSE (CMAKE_TEST_BITS_ATOMIC_CXX)
    MESSAGE(STATUS "Check for <bits/atomicity.h>  CXX namespace - not found")

  ENDIF (CMAKE_TEST_BITS_ATOMIC_CXX)

IF(HAVE_GCC_BITS_ATOMIC_VOID)
 IF(HAVE_GCC_BITS_ATOMIC_CXX)
 file(APPEND ${CMAKE_SOURCE_DIR}/config.h "#define KOL_HAVE_GCC_BITS_ATOMIC_CXX 1\n" )
 ELSE(HAVE_GCC_BITS_ATOMIC_CXX)
 file(APPEND ${CMAKE_SOURCE_DIR}/config.h "#define KOL_HAVE_GCC_BITS_ATOMIC 1\n" )
 ENDIF(HAVE_GCC_BITS_ATOMIC_CXX)
ENDIF(HAVE_GCC_BITS_ATOMIC_VOID)
